### ISSUE TITLE
Import of configurable products partially broken

### ISSUE THREAD

**Issue by dimonixx** [oroinc/orocommerce#116]
**Summary**  
since  the changes in https://github.com/oroinc/orocommerce/blob/a254632a1d0683bc28f50ae6c6b142bc895be26f/src/Oro/Bundle/ProductBundle/Entity/ProductVariantLink.php#L142 and adding the parent variant link to the child import of configurable products is broken if an invalid configurable exists in an import batch.

- an invalid configurable is not being persisted
- the simple product , after [addParentVariantLink](https://github.com/oroinc/orocommerce/blob/a254632a1d0683bc28f50ae6c6b142bc895be26f/src/Oro/Bundle/ProductBundle/Entity/ProductVariantLink.php#L142), still contains the _variantLink_ with an unmanaged _parentProduct_ in the _parentVariantLinks_ collection 
- the simple product is being persisted and during flush `A new entity was found through the relationship` exception occurs.

**Steps to reproduce**  
cli import a csv file with configurable products with at least 1 invalid configurable product

**Actual Result**
none of the products are imported.
Following exception is thown:
` [Doctrine\ORM\ORMInvalidArgumentException]
  A new entity was found through the relationship 'Oro\Bundle\ProductBundle\Entity\ProductVariantLink#parentProduct'`

**Expected Result**  

**Details about your environment**
- starting from OroCommerce version: 3.1.16 CE / Enterprise
- PHP version: 7.2.*

**Comment by anyt** [comment]
Internal ticket id #BB-19380.

**Comment by anyt** [comment]
Fixed in 3.1.24 (enterprise edition only) and 4.1.6. Thank you!
