### ISSUE TITLE
3.x branch is not installable due to absence of https://github.com/qodeboy-forks/elevatezoom.git/

### ISSUE THREAD

**Issue by calve** [oroinc/orocommerce#127]
**Summary**

Versions 3.1.xx fails to install. Installation fails with 

```
$ composer create-project oro/commerce-crm-application=3.1.20 orocrm --repository=https://satis.oroinc.com --no-interaction --prefer-dist --no-dev --remove-vcs
   [....]

  - Installing bower-asset/elevatezoom3 (3.0.8.1): Cloning e02b7785a3

                                                                                                        
  [RuntimeException]                                                                                    
  Failed to clone https://github.com/qodeboy-forks/elevatezoom.git via https, ssh protocols, aborting.  
                                                                                                        
  - https://github.com/qodeboy-forks/elevatezoom.git                                                    
    Cloning into '/var/www/html/orocrm/vendor/bower-asset/elevatezoom3'...                              
    remote: Invalid username or password.                                                               
    fatal: Authentication failed for 'https://github.com/qodeboy-forks/elevatezoom.git/'                
                                                                                                        
  - git@github.com:qodeboy-forks/elevatezoom.git                                                        
    Cloning into '/var/www/html/orocrm/vendor/bower-asset/elevatezoom3'...                              
    error: cannot run ssh: No such file or directory                                                    
    fatal: unable to fork       
```

It looks like this repository does not exists anymore. https://github.com/elevateweb/elevatezoom exists
  
**Steps to reproduce**  
Run `composer create-project oro/commerce-crm-application=3.1.20 orocrm --repository=https://satis.oroinc.com --no-interaction --prefer-dist --no-dev --remove-vcs`

**Actual Result**

Installation fails

**Expected Result**  

Installation succeed. To prevent this in the future, I suggest to build and distribute assets in the orocommerce distribution.

**Comment by anyt** [comment]
OroCommerce 3.1 is not supported anymore. We recommend upgrading to 4.1 LTS or to 4.2.0-RC, which will become the next LTS release in less than two weeks.

The issue is not related to the application itself. For some reason, the maintainer of elevatezoom NPM module decided to drop it.

**Comment by calve** [comment]
Thanks for the quick reply. https://doc.oroinc.com/community/release-process/ mentions support for 3.1 until january 2022 but I understand that branch is not maintened anymore.
