### ISSUE TITLE
Typo error in OroFrontendImportExportBundleInstaller.php namespace 

### ISSUE THREAD

**Issue by damien-louis** [oroinc/orocommerce#137]
Typo error in namespace for 
https://github.com/oroinc/customer-portal/blob/4.2.4/src/Oro/Bundle/FrontendImportExportBundle/Migrations/Schema/OroFrontendImportExportBundleInstaller.php

`namespace Oro\Bundle\FrontendImportExportBundle\Mirgations\Schema;` (Mi**rg**ations)

**Comment by anyt** [comment]
Thank you, Damien, 
It will be fixed in 4.2.6. The issue is minor, and as I understand, it does not affect the upgrade procedure because the migration is executed properly anyway.

**Comment by damien-louis** [comment]
Thanks
