### ISSUE TITLE
just installed 5.0.0    login page stucks on Loading...

### ISSUE THREAD

**Issue by ismetsener** [oroinc/orocommerce#144]
**Summary**  

I jus installed OROcommerce 5.0.0 and after installing i try to login.
http://192.168.2.31/admin/user/login
but I get a empty page with the next message:
Loading...

I found some information, but it did not help
https://forum.oroinc.com/orocrm/orocrm-installationtechnical-issues-or-problems/topic/stuck-on-loading...-after-login/

**Steps to reproduce**  

**Actual Result**

**Expected Result**  

**Details about your environment**
- OroCommerce version: x.y.z
- PHP version: x.y.z
- Database (MySQL, PostgreSQL) version

**Additional information**

**Comment by anyt** [comment]
Please fill in the "Details about your environment" in the issue template, they are required to solve the issues as the application is used among various environments.

Also, check the browser console for errors. Most likely application it's a webserver configuration issue or assets were not built during installation and you have to rebuild them manually by running `php bin/console oro:assets:build --env=prod`.

**Comment by ismetsener** [comment]
Hello,
thanks for your answer, 
you can see my details about my environment above

after running command: php bin/console oro:assets:build --env=prod
I got error message:

php bin/console oro:assets:build --env=prod
Building assets.
'/usr/bin/node' './node_modules/webpack/bin/webpack.js' '--mode=production' '--env' 'symfony=prod' 'skipBabel'
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/opt/orocommerce/node_modules/webpack/bin/webpack.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

In OroAssetsBuildCommand.php line 257:

  Build failed.


oro:assets:build [-w|--watch] [--hot] [--key KEY] [--cert CERT] [--cacert CACERT] [--pfx PFX] [--pfxPassphrase PFXPASSPHRASE] [-f|--force-warmup] [-i|--npm-install] [--skip-css] [--skip-js] [--with-babel] [--skip-sourcemap] [--skip-rtl] [--analyze] [--] [<theme>]

**Comment by ismetsener** [comment]
problem solved:
by installing:
npm install webpack

thanks
