### ISSUE TITLE
Oro Migration getting failed when running oro:install command for version 5.1LTS 

### ISSUE THREAD

**Issue by sonalpadole-vertex** [oroinc/orocommerce#161]
**Summary**  
I was trying to upgrade to Oro enterprise version 5.1 from 5.0.10 but it continuously throws one or the other error. So I tried with the fresh install of version 5.1.0. When I execute below command :
`php bin/console oro:install --env=prod --timeout=2000`

It gives me this error- 
 ```
ERROR: An exception occurred while executing 'CREATE INDEX website_search_result_history_term_lower_idx ON oro_website_search_result_history (LOWER("search_term"))':
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"search_term"))' at line 1
```
![image](https://github.com/oroinc/orocommerce/assets/87015218/75135e7f-f8d3-4b0d-8dbd-847f47ddec67)

**Expected Result**  
I recently upgraded smoothly to 5.0.10 version but facing issues with 5.1. Upgarde and install should work smothly.. Can someone help me with this issue. It's a blocker for me.

**Details about your environment**
- OroCommerce version: 5.1
- PHP version: 8.2
- Database (MySQL) version - 8.0.26

**Additional information**

**Comment by anyt** [comment]
Hi @sonalpadole-vertex,
MySQL is not supported in v5.1.
It is required [migrating the database to PostreSQL](https://doc.oroinc.com/backend/setup/mysql-to-postgresql/) before he upgrade.
