### ISSUE TITLE
OroCommerce 4.2:  Export Price List. Error: Orphans were found and redelivered. consumerIds:.....

### ISSUE THREAD

**Issue by diegovanz** [oroinc/orocommerce#163]
I have a problem, it does not export the price lists and it reports the following error by mail.

Orphans were found and redelivered. consumerIds: "64939fec392e05.70085169, 6493a055b7ec90.88552179, 6493a05d9431a4.72716877"

extension: | Oro\Component\MessageQueue\Consumption\Dbal\Extension\RedeliverOrphanMessagesDbalExtension

**Comment by mbessolov** [comment]
Hello diegovanz,

If you are an OroCommerce Enterprise Edition customer, please submit this issue to the customer support portal.

If you are using the Community Edition, please note that support for 4.2 Community Edition ended more than a year ago - https://doc.oroinc.com/community/release-process/#orocommerce-community-edition-releases

There have been a few fixes for similar issues in 5.0 and 5.1, but without clear description of the environment and steps to reproduce the problem it is hard to say which fix would be more relevant to this problem.

I suggest you check if the problem can still be reproduced in the most recent 5.1 release (5.1.0 at the time of writing).

Thank you
