### ISSUE TITLE
HTML editor errors on ">" in Twig blocks

### ISSUE THREAD

**Issue by Dr-Head** [oroinc/orocommerce#32]
When editing HTML templates the editor has an issue with converting the greater than symbol "<" to "&gt;" Which doesn't work for twig code blocks.

Line that the editor converts:
`<p>{{ payment_methods[0] }} {% elseif payment_methods|length > 1 %}</p>`

Resulting error:
`The template for Content (English) has syntax error: Unexpected character "&" at line 14.`
When you open the HTML editor again you can see that the > was converted to "&gt;"

This can be observed by:

1. going to the "admin/email/emailtemplate/" 
2. opening 'Edit email template "order_confirmation_email"'
3. Click the "Edit Source button" <>
4. Make no changes but click "Ok"
5. Try closing and saving the template.

**Comment by mkudelya** [comment]
Hi @Dr-Head 

Thank you for reporting the issue.

**Comment by manowark** [comment]
Internal ID: BAP-14796

**Comment by sprightly** [comment]
Hello.
Until issue will be fixed this is possible to use next workaround.
Go to System Configuration > General Setup > Display Settings and uncheck "Enable WYSIWYG Editor".
Then create your email templates, save it and then you can enable WYSIWYG back again.

**Comment by sprightly** [comment]
Hello.
Issue were fixed. Please reopen this ticket or create new if some problems persists.
