### ISSUE TITLE
Can not load prices for Product after Quote page loaded

### ISSUE THREAD

**Issue by lbond** [oroinc/orocommerce#46]
https://github.com/orocommerce/orocommerce/blob/469bb09cb9305a2b9417309f5d4b83da89ac3909/src/Oro/Bundle/SaleBundle/Resources/views/Quote/update.html.twig#L80

I think that ajax parameters was missed (We should pass also customer and currency):
` <div class="quote-lineitems"
             data-page-component-module="oroui/js/app/components/view-component"
             data-page-component-options="{{ {
                 view: 'orosale/js/app/views/line-items-view',
                 tierPrices: tierPrices|default({}),
                 tierPricesRoute: 'oro_pricing_price_by_customer',
                 customer: entity.customer is null ? null : entity.customer.id,
                 currency: entity.currency
             }|json_encode }}"
             data-layout="separate">
            {{ form_widget(form.quoteProducts) }}
            {{ form_errors(form.quoteProducts) }}
        </div>`
Now it works ok (Ajax has a right response) but UI element should be updated. I think that should be called also "oro_quote_entry_point" request

**Comment by lbond** [comment]
PR for the backend part: https://github.com/orocommerce/orocommerce/pull/48

**Comment by x86demon** [comment]
Hi, @lbond 
Thank you for reporting issue.
Internal ID: BB-12350

**Comment by yurio** [comment]
Hi, @lbond. Your commit was moved to Oro development repository and in several weeks it will appear in public platform repository.

Thank you one more time for your contribution.
