### ISSUE TITLE
Orders API doesn't have internal status attribute

### ISSUE THREAD

**Issue by arthurpro** [oroinc/orocommerce#52]
The addition of internal statuses in v1.4 for orders is awesome, but status is not returned via the API request to `GET /admin/api/orders`
This makes life very difficult. And also you cannot filter orders by status.

**Comment by NiMias** [comment]
Hello, @arthurpro .
Thank you for your report.
Created internal task fix the problem (id: BB-12464 to).

**Comment by ecin1jgle1** [comment]
We absolutely must have order status visible and modifiable through the API.  We also must be able to define a have a custom order status to mark orders imported from Oro Commerce to an external system.
