### ISSUE TITLE
Order totals wrong calculated 

### ISSUE THREAD

**Issue by dimonixx** [oroinc/orocommerce#54]
Using option `Product prices include tax` results to wrong calculation of Order Totals, whereby taxes are calculated the right way:

<img width="348" alt="bildschirmfoto 2017-11-10 um 20 07 33" src="https://user-images.githubusercontent.com/5039867/32674343-170fd416-c653-11e7-91c8-b1848ef42ef0.png">
<img width="371" alt="bildschirmfoto 2017-11-10 um 20 07 43" src="https://user-images.githubusercontent.com/5039867/32674344-17291d90-c653-11e7-9afc-fb92087c9ea6.png">

**Comment by dimonixx** [comment]
[TaxSubtotalProvider](https://github.com/oroinc/orocommerce/blob/2b18fc66127cef7f4ba3d468f57e05cdecea8827/src/Oro/Bundle/TaxBundle/Provider/TaxSubtotalProvider.php#L108)  doesn't take in account the setting  `oro_tax.product_prices_include_tax`

In case `oro_tax.product_prices_include_tax=1` the operation of Subtotal should be OPERATION_IGNORE, as the lines subtotal has already taxes.

| subtotal | amount |
|----------|-------|
| subtotal | 10,00 |
| tax      | 0,65  |   |
| shipping | 3,99  |
| total    | 13,99 |

If the customer buys goods without taxes and `oro_tax.product_prices_include_tax=1` the operation would be OPERATION_SUBTRACTION.

| subtotal | amount |
|----------|-------|
| subtotal | 9,35 |
| shipping | 3,99  |
| total    | 13,34 |

**Comment by alexandr-parkhomenko** [comment]
Hello, @dimonixx .
Thank you for your report.
Created an internal task to fix the problem (id: BB-12882).

**Comment by anyt** [comment]
Fixed in https://github.com/oroinc/orocommerce/commit/ffed4edd4838826dd98e258f7f7a385d99fc3f54 
Thank you!
