### ISSUE TITLE
Orocommerce installation failed at Load translations on final installation step

### ISSUE THREAD

**Issue by tijopromantia** [oroinc/orocommerce#55]
The installation have been stopped on load translation failed on 5th stage( finish stage) and cannot proceed further.
OS- ubuntu 16.04
php - 7.0
orocommerce 1.4

**Comment by jarl1** [comment]
Thank you for reporting. Please provide more details about bug. Is there any message? PHP error?

**Comment by tijopromantia** [comment]
I had checked /var/log/apache2/error.log

"The HOME or COMPOSER_HOME environment variable must be set for composer to
run correctly"

Got this error.

Thanks & Regards
Tijo Joel Verghis

**Comment by jarl1** [comment]
It's not related to OroCommerce. You have bad configuration on you server. Check if you have fresh composer or try to set COMPOSER_HOME=~/.composer. Maybe you need download composer manually instead using ubuntu package manager.

**Comment by tijopromantia** [comment]
Thank you I will check and revert


Thanks & Regards
Tijo Joel Verghis
