### ISSUE TITLE
Edit customer user permission.

### ISSUE THREAD

**Issue by xgitxhubx** [oroinc/orocommerce#56]
Can buyer role customer users edit other customer users?
![buyer](https://user-images.githubusercontent.com/30398975/33366183-0fd6e792-d51d-11e7-8481-b93018ca13b7.png)
![role](https://user-images.githubusercontent.com/30398975/33366184-1007c646-d51d-11e7-958c-d308c5244ab8.png)

If not, how to change password?

**Comment by mbessolov** [comment]
These capabilities will be decoupled in the upcoming 1.5 release. There will be a separate 'Update User Profile' permission.

**Comment by xgitxhubx** [comment]
Thanks @mbessolov
