### ISSUE TITLE
Entity didn`t show in customerUserRole

### ISSUE THREAD

**Issue by vafabandi** [oroinc/orocommerce#62]
Hi everyone,
In edit and view of customeUserRole entities would not appear. Can anyone help me with why this is happening?
thanks,
vafa

**Comment by aalgogiver** [comment]
Hi, @vafabandi. Have you noticed any errors in developer's console or application logs?

**Comment by dimonixx** [comment]
Hi, @vafabandi ,
have you imported roles or created them in backend ?
