### ISSUE TITLE
On installation: 'Oro\Bundle\RedisConfigBundle\OroRedisConfigBundle' not found

### ISSUE THREAD

**Issue by vaidascizikas** [oroinc/orocommerce#68]
During fresh install on a server:
1. before installing, I've changed composer.json as such - https://github.com/oroinc/platform-application/pull/16/commits/67c1ea6845408ed270069bc958856ea07618bb32 (otherwise composer install gets errors)

2. git clone --recursive https://github.com/orocommerce/orocommerce-application.git - OK
3. composer install --prefer-dist --no-dev - OK
4. php app/console oro:install --env=prod - FAIL, got an error:

PHP Fatal error:  Uncaught Error: Class 'Oro\Bundle\RedisConfigBundle\OroRedisConfigBundle' not found in /var/www/html/app/cache/prod/bundles.php:17

on bundles.php:17 we have
<...>
new Oro\Bundle\RedisConfigBundle\OroRedisConfigBundle(),
<...>

Tried few times in two environments - same results always.

**Comment by bemzaslava** [comment]
Hello, @vaidascizikas !
Thank you for reporting the issue.

Unfortunately, at the moment the master branch has broken dependencies, it will be fixed in the near future.

At the moment I recommend using the latest release branch, 1.6

**Comment by anyt** [comment]
The issue already fixed here https://github.com/oroinc/platform-application/blob/67c1ea6845408ed270069bc958856ea07618bb32/composer.json#L37,
Thank you!
