### ISSUE TITLE
crud on frontend

### ISSUE THREAD

**Issue by vafabandi** [oroinc/orocommerce#69]
hello everybody,
I have a entity and I want to have crud functions on frontend view. (with layouts)
can anyone help me ?

**Comment by yurio** [comment]
Hello, @vafabandi.

You can have a loon onto frontend CustomerUserRoleController

https://github.com/oroinc/customer-portal/blob/2.4.1/src/Oro/Bundle/CustomerBundle/Controller/Frontend/CustomerUserRoleController.php

**Comment by mbessolov** [comment]
I am now closing this issue as it has been inactive for a while. Please feel free to reopen it if you have any questions.
