### ISSUE TITLE
Oro commerce don't open link from dashboard and menu

### ISSUE THREAD

**Issue by petarkozic** [oroinc/orocommerce#70]
I have fresh installed oro commerce on nginx.
I'm do everything from manual.

I can open homepage and I can to login into /admin
but if I click on some link that link don't open, also I can goes over menu items but if I click on some item, nothings happend.
If I try to open that link in new tab or copy and paste that link in browser than works.

Really stupid problem.
Please can someone help me.
Thank you.

**Comment by vitaliyberdylo** [comment]
Hello. petarkozic.
Your description of issue is, unfortunately, not enough to understand what is wrong. Could you please show me a more detailed error which could be appeared in Chrome/Firefox DevTools?

**Comment by petarkozic** [comment]
Hello @vitaliyberdylo 
I don't have any error which I can send to you.
Simple, if mouse over some menu item or dashboard buttons I can see in status bar links, but if I click nothings hapends.
If I copy that link and paste in new tab, then works.

**Comment by vitaliyberdylo** [comment]
Probably a problem in the web server settings
Please stop nginx.
And run PHP build-in web server.
`php app/console s:r` 
And recheck links, they will have to work correctly.

**Comment by vitaliyberdylo** [comment]
Just in case, in order to convince that the application was previously correctly installed run command
`php app/console oro:platform:update --force`

**Comment by petarkozic** [comment]
@vitaliyberdylo 
I was tried with this 
`php app/console oro:platform:update --force`
but don't help me.

I can't run `php app/console s:r` because I'm afraid for other sites. On this server I have several sites hosted.

`PHP 7.1.14-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  9 2018 09:33:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.14-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies`

nginx configuration was build with manual from your sites. Php works, I can open phpinfo page, also Dashboard and admin page was regular opens.

**Comment by vitaliyberdylo** [comment]
@petarkozic 
Please open browser DevTools tab Network.
Click on not working navigation link.
Check was the AJAX request.
Check response. (There is a possibility that it is something like {a:1}PHP Warning ... in responce)

Also you can compare with response 
for the same request on https://demo.orocommerce.com/admin/attribute/family/index/product

**Comment by petarkozic** [comment]
@vitaliyberdylo 
I don't have anything in Network tab when I click on link.
Nothing happens when I click on link.

I supposed that something with `try_files` in nginx, but everything is setup as in manual.

Also, if I click in calendar on button New event where is javascript that works !

**Comment by vitaliyberdylo** [comment]
@petarkozic
Try open browser in incognito mode and recheck.
Also, if it possible, can you provide link to you website.

**Comment by petarkozic** [comment]
@vitaliyberdylo 
In incognito when I login I see this error:

`The application is not configured properly (message consumers are not available). Please contact the system administrator.
Dashboards/  Dashboard
`

**Comment by petarkozic** [comment]
@vitaliyberdylo 
https://oro.bluetrade.eu/admin

user: admin
pass: admin123

**Comment by vitaliyberdylo** [comment]
@petarkozic 
Looks like the problem is in Rocket Loader.
Can you turn off it?

**Comment by petarkozic** [comment]
@vitaliyberdylo 

> Looks like the problem is in Rocket Loader.
Can you turn off it?

Thank you ! This is solution for my problem !
