### ISSUE TITLE
Widget content loading failed (add language)

### ISSUE THREAD

**Issue by petarkozic** [oroinc/orocommerce#72]
When I try to add new language, French. I got error
`Widget content loading failed `

In inspect tab I can see blocked mixed content:
`Mixed Content: The page at https://...  was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint http://......`

Orocommerce was installed with --application-url="https://...."

Some idea ?

**Comment by vladimirseniuk** [comment]
Hi @petarkozic,

Сan you specify which version of OroCommerce you are using?
Also you can help if you describe steps of installation.

Thank you!

**Comment by petarkozic** [comment]
Domain was on cloudflare.
Problem is resolved forcing all traffic over https on cloudflare.
Thanks @vladimirseniuk
