### ISSUE TITLE
Typo in system_configuration.yml of ShippingBundle

### ISSUE THREAD

**Issue by alexandrzhulev** [oroinc/orocommerce#76]
Found a typo in
https://github.com/oroinc/orocommerce/blob/ca0f7c24e07d4658d09abdbeef1a348d231f96d3/src/Oro/Bundle/ShippingBundle/Resources/config/oro/system_configuration.yml#L54
(used `priotity` instead of `priority`)

**Comment by michaelfi** [comment]
Vielen Dank fuer die Nachricht. / Thank you for your message.

Ich bin bis einschließlich 11.6.2018 nicht erreichbar und melde mich nach meiner Rueckkehr bei Ihnen.
Ihre Nachricht wird nicht gelesen und weitergeleitet. In dringenden Faellen melden Sie sich bitte unter +49 221 2784 6667.

I'm currently out of office and will reply after my return on 12th June 2018.
Your Message will not be read and forwarded. In urgent matters, please contact +49 221 2784 6667.

Freundliche Grueße / Best
Michael Fluck

**Comment by anyt** [comment]
Fixed https://github.com/oroinc/orocommerce/commit/ec79785ee5b96935aed895ff7b55bee45eb5ec46,
Thank you for the report!
