### ISSUE TITLE
Consumer interrupted, after saving a product attribute

### ISSUE THREAD

**Issue by dimonixx** [oroinc/orocommerce#77]
OroCommerce 3.0-rc:

when saving in backend a product attribute of type select, message consumer is interrupted with following message:

`WARNING  : Consuming interrupted, reason: The cache has changed.`

The attribute is saved succesfuly.

**Comment by anyt** [comment]
Interruption is a part of consumer life cycle.
It's recommended to configure supervisor to start consumer automatically on interruption.
https://github.com/oroinc/platform/tree/master/src/Oro/Bundle/MessageQueueBundle#supervisord

**Comment by dimonixx** [comment]
Sure , it should be interrupted, when cache is updated. But why does this happen, when adding an attribute in the backend ? 
When using the supervisor, how to recognize , if the consumer can be restarted or not, depending on how critical was the error ?

**Comment by anyt** [comment]
> When using the supervisor, how to recognize , if the consumer can be restarted or not, depending on how critical was the error ?
Consumer always should be restarted after interruption.
https://github.com/laboro/dev/blob/master/package/platform/src/Oro/Bundle/MessageQueueBundle/Resources/doc/logging.md#consumer-interruption
