### ISSUE TITLE
Configurable products are not imported

### ISSUE THREAD

**Issue by dimonixx** [oroinc/orocommerce#78]
OroCommerce 3.0-rc

i've created  two products configurable and  simple, the simple one , is a variant of the configurable.
Running export results a file with 2 products, during import the file only 1 product is created, the simple one, configurable is not imported/created.

**Comment by dimonixx** [comment]
The product's export file did not contain variantLinks column at all. I've created an import file manually - variants were imported.

**Comment by michaelfi** [comment]
Vielen Dank fuer die Nachricht. / Thank you for your message.

Ich bin bis einschließlich 17.8.2018 nicht erreichbar und melde mich nach meiner Rueckkehr bei Ihnen.
Ihre Nachricht wird nicht gelesen und weitergeleitet. In dringenden Faellen melden Sie sich bitte unter +49 221 2784 6667.

I'm currently out of office and will reply after my return on 17th August 2018.
Your Message will not be read and forwarded. In urgent matters, please contact +49 221 2784 6667.

Freundliche Grueße / Best
Michael Fluck

**Comment by artml** [comment]
@dimonixx this is not a bug, rather a feature not yet implemented. We deemed the use case of exporting product variants less important than import and so implemented only the latter.

There are no immediate plans to implement export of configurable product variants, but stay tuned to our updates as this feature remains in our backlog. Thank you!
