### ISSUE TITLE
Typo in SaleBundle Validation Message

### ISSUE THREAD

**Issue by chrisaligent** [oroinc/orocommerce#91]
Just came across this typo:
![image](https://user-images.githubusercontent.com/45612883/52541340-b8a29680-2de3-11e9-869d-2890cb5d0a27.png)

It should say "greater than", not "grater than".
Looks like it's been there since September 2015.
https://github.com/oroinc/orocommerce/search?q=grater&unscoped_q=grater

**Comment by anyt** [comment]
Fixed in #92
