### ISSUE TITLE
[ACL] user can see Product families from other organization

### ISSUE THREAD

**Issue by tautelis** [oroinc/orocommerce#96]
Reproduce:
* given you have two organizations
* user belongs to organization A only
* user goes to /admin/attribute/index/product
* in the "Product families" column user sees organization B product families

**Comment by anyt** [comment]
Hi @tautelis,

Confirmed the bug. However, this repository must contain only Community Edition code and issues.
As multi-organization is an enterprise feature, please report it to [an Enterprise Customers Support Portal](https://magecore.atlassian.net/servicedesk/customer/portal/2/) or [Partners Support Portal](https://magecore.atlassian.net/servicedesk/customer/portal/3).

Thank you!

**Comment by tautelis** [comment]
I am not an enterprise user, so you should manage it yourself then :)

**Comment by anyt** [comment]
Community edition supports only one organization. Bugs related to enterprise features can be reported only by enterprise customers. If you somehow managed to make multiorganization work in CE, you should support it by yourself. There is nothing I can help you with here.
