### ISSUE TITLE
Import configurable products from command line not possible since 3.1.9

### ISSUE THREAD

**Issue by dimonixx** [oroinc/orocommerce#98]
Since OroCommerce 3.1.9 the configurable  products are postponed in the strategy.

When importing from command line:

The `PostponedRowsHandler` always creates the message with [`Topic::HTTP_IMPORT`](https://github.com/oroinc/platform/blob/fdd175c7e72d297c39cd92799893e9a6fbe9728e/src/Oro/Bundle/ImportExportBundle/Handler/PostponedRowsHandler.php#L136) , what causes the postponed job fail because it's beeing processed by wrong processor.

The message is being processed by [`HttpImportMessageProcessor`](https://github.com/oroinc/platform/blob/fdd175c7e72d297c39cd92799893e9a6fbe9728e/src/Oro/Bundle/ImportExportBundle/Async/Import/HttpImportMessageProcessor.php), the message validation fails because the `userId` key does not exist in the message body.

**Comment by dxops** [comment]
_Internal ID: BAP-19180_

**Comment by anyt** [comment]
Fixed in 3.1.12. Thank you!
